
#source "https://rubygems.org"

#gem "jekyll"  
#gem "jekyll-paginate"
#gem "jekyll-gist"
#gem "redcarpet"
#gem "pygments.rb"

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"





