locale: "en"
lang: "en-us"
repository: marisavas/marisavas.github.io
baseurl: "" # the subpath of your site, e.g. /blog
title: "Marisa Vasconcelos" # the name of your site
description: >- # this means to ignore newlines until "baseurl:"
   Marisa Vasconcelos site.
# domain: marisavas.github.io
url: https://marisavas.github.io  # the base hostname and protocol for your site

permalink: '/:title/'

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-scholar


scholar:
  style: _bibliography/springer-lecture-notes-in-computer-science2.csl
  locale: en
  # source: ./_bibliography
  bibliography_template: bib
  query: "@*"
  sort_by: year, month
  order: descending, descending
  replace_strings: true
  join_strings: true

font-awesome:
  assets: true

google_analytics: G-2ZK8Y6NZWJ
