title: Welcome to Flexton
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: ''

domain: marisavas.github.io
url: https://marisavas.github.io  # the base hostname and protocol for your site, e.g. http://example.com


author-name: Marisa Vasconcelos
author-image: marisavasconcelos.png
author-job: Social Computing Researcher
about-author: >-
  I am a web developer focusing on front-end development. Always hungry to keep
  learning.
social-twitter: artemsheludko_
social-facebook: null
social-github: artemsheludko
social-pinterest: artemsheludko
social-instagram: artemsheludko_
social-youtube: null
social-vk: null
social-linkedin: null
mailchimp: null
google-analytics: null
disqus-identifier: mr-brown
markdown: kramdown
permalink: '/:year/:month/:day/:title/'
plugins:
  - jekyll-paginate
  - jekyll-scholar
paginate: 7
paginate_path: '/page/:num/'
future: true
scholar:
  style: _bibliography/springer-lecture-notes-in-computer-science2.csl
  locale: en
  source: ./_bibliography
  bibliography_template: bib
  query: "@*"
  sort_by: year, month
  order: descending
  group_by: none
  group_order: ascending
  repository: /publications
  replace_strings: true
  join_strings: true



include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
