#Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           pretty
# relative_permalinks: true


# Setup
title:               Marisa Vasconcelos
tagline:             Site
url:                 https://marisavas.github.io
baseurl:             '/'

defaults:
  - scope:
      path: publications.md
    values:
      menu: true
      order: 1

  - scope:
      path: projects.md
    values:
      menu: true
      order: 2
# menu:
#   - title: Home
#     url: /home/
#   - title: Publications
#     url: /publications/
#   - title: Projects
#     url: projects

# About/contact
author:
  name:              Marisa Vasconcelos
#   url:               https://twitter.com/mdo
#   email:             markdotto@gmail.com

paginate: 5
# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/marisavas/marisavas.github.io.git

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
