
source "https://rubygems.org"

gem "jekyll"  
gem "jekyll-paginate"
gem "jekyll-gist"
gem "redcarpet"
gem "pygments.rb"

title: Marisa Vasconcelos
google_analytics: [Your Google Analytics tracking ID]
markdown:         redcarpet
pygments:         true
highlighter:      pygments

# Permalinks
permalink:        pretty


