roles:
  - name: Organization
    description:
      - { text: Workshop Women in Data Science at The Web Conference (2018-2020) }
      - { text: Workshop Women in Data Science at SIAM SDM (2017) }

  - name: Editorial Board
    description:
      - { text: IEEE Transactions on Technology and Society }

  - name: Program Commitee
    description:
      - { text: The Web Conference (2021-2022) }
      - { text: ICWSM (2021-present) }
      - { text: IEEE/ACM ASONAM (2019-2021) }
      - { text: DEVIANCE Workshop @IEEE-BigData (2020) }
      - { text: BAAI @EPIA (2017, 2019)}
      - { text: PAPi LATAM (2019)}

  - name: Journal Reviewer
    description:
      - { text: PLOS ONE (2020 - present)}
      - { text: ACM Transactions on Social Computing (TSC) (2019 - present)}
      - { text: ACM Transactions on Internet Technology (TOIT) (2019)}
      - { text: Elsevier Information Processing & Management (2018)}

talks:
  - date: March 2023
    title: Round table with undergraduate students about Opportunities and Perspectives in CS, UFMG, Belo Horizonte, Brazil

  - date: March 2022
    title: Misinformation Dissemination on WhatsApp Groups, Universidad Pompeu Fabra, Spain

  - date: October 2021
    title: Misinformation Dissemination on WhatsApp Groups, Saint Louis University, USA

  - date: February 2021
    title: Misinformation Dissemination on WhatsApp Groups, Universidad Pompeu Fabra, Spain

  - date: November 2019
    title: Women in Technology. Invited Panelist, Education Show (LER), Rio de Janeiro, Brazil

  - date: October 2019
    title: Artificial Intelligence Concepts, Applications and Challenges. IBM Diversity Week, Sao Paulo, Brazil

  - date: May 2019
    title: Artificial Intelligence Inclusion Challenges. Swissness, Sao Paulo, Brazil

  - date: April 2019
    title: From Social Data Bias to Algorithm Discrimination. UFMG, Belo Horizonte, Brazil

  - date: August 2017
    title: Big Data Applications. IBM, Sao Paulo, Brazil

  - date: October 2016
    title: Women in Computer Science. UFMG, Belo Horizonte, Brazil

awards:
  - date: 2020
    description: Fourth Plateau - Invention Achievement Awards in appreciation and recognition of creative contributions to IBM progress.

  - date: 2019
    description: Honorable Mention on Published Paper at CHI'19.

  - date: 2013 – 2014
    description: InWeb (National Institute of Science and Technology for the Web). Ph.D. Research Fellowship for support graduate studies, Brazil.

  - date: 2012
    description: 2nd Best Ph.D. Work at Graduate Week. Computer Science Department at Universidade Federal de Minas Gerais, Brazil.

  - date: 2011
    description: Google Women in Technology Award (Anita Borg). Google Brazil Winner, Brazil.

  - date: 2010
    description: Hewlett-Packard Labs. Research Fellowship from HP-Labs in joint project with Universidade Federal de  Minas Gerais, Brazil.

  - date: 2009 – 2013
    description: FAPEMIG (Brazilian Foundation for Research Support). Ph.D. Research Fellowship for support for graduate studies, Brazil

  - date: 2006 – 2008
    description: Fulbright (U.S Department of State) and CAPES (Brazilian Federal Agency for Support and Evaluation of Graduate Education). M.A. Research Scholarship support graduate studies, USA.

  - date: 2006 - 2008
    description: Boston University. M.A. Tuition Fellowship support for graduate studies, USA.

  - date: 2001 - 2003
    description: CAPES (Federal Agency for Support and Evaluation of Graduate Education). M.Sc. Research Fellowship support for graduate studies, Brazil.

  - date: 2000 – 2001
    description: FAPEMIG (Brazilian Foundation for Research Support) support to scientific investigation during undergraduate studies, Brazil.

  - date: 1998 –  2000
    description: CNPQ (National Council for Scientific and Technological Development) support to scientific investigation during undergraduate studies, Brazil.
