title: Marisa Vasconcelos
description:
baseurl: ''

domain: marisavas.github.io
url: https://marisavas.github.io  # the base hostname and protocol for your site, e.g. http://example.com


author-name: Marisa Vasconcelos
author-image: marisa_vasconcelos.png
author-job: Social Computing Researcher
about-author: >-
  My name is Marisa Vasconcelos. I'm a social computing researcher and a research scientist at IBM Research Labs in Brazil. I am interested in using social data to understand people's behavior, focusing on societal problems such as misinformation dissemination, hate speech, and gender inequality.
social-twitter: marisavas
social-facebook: null
social-github: null
social-pinterest: null
social-instagram: null
social-youtube: null
social-scholar: user=e5IvuJgAAAAJ
social-linkedin: marisa-affonso-vasconcelos-0116b16
mailchimp: null
google-analytics: null
disqus-identifier: mr-brown
markdown: kramdown
permalink: '/:year/:month/:day/:title/'
plugins:
  - jekyll-paginate
  - jekyll-scholar
paginate: 7
paginate_path: '/page/:num/'
future: true
scholar:
  style: _bibliography/springer-lecture-notes-in-computer-science2.csl
  locale: en
  source: ./_bibliography
  bibliography_template: bib
  query: "@*"
  sort_by: year, month
  order: descending
  group_by: none
  group_order: ascending
  repository: /publications
  replace_strings: true
  join_strings: true


font-awesome:
  assets: true

include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
