source "https://rubygems.org"

gem 'bundler'
gem 'jekyll'
gem 'jekyll-paginate'
gem 'jekyll-scholar', group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'public_suffix', '~> 4.0.6'

# Added at 2021-06-07 10:47:12 -0300 by marisavasconcelos:
gem "webrick", "~> 1.7"
