# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: List files
        run: |
          ls -la
          
       
      
      - name: Configure Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 0 
          bundler: "Gemfile.lock"
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      - name: Install dependencies
        run: | 
          bundle config set path 'vendor/bundle' 
          bundle install
          
      - name: Build Jekyll site
        run: | 
          bundle exec jekyll build || { echo 'Jekyll build failed'; exit 1; }
          ls -al _site

      - name: List contents after build
        run: ls -R    
        
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site  
          target_branch: gh-pages
          keep_files: true

        
